;rm1.sc

f1  0  4096  10  1

i2    0     6    2000    440                    ;tone 1
i2    3     3    2000    163                    ;tone 1+tone2
i1    6     4    2000    440      10       163  ;tone 1*tone2
s
i2    0     6    2000    440                    ;tone 1
i2    3     3    2000    420                    ;tone 1+tone2
i1    6     4    2000    440      10       420  ;tone 1*tone2
s
i2    0     6    2000    440                    ;tone 1
i2    3     3    2000     20                    ;tone 1+tone2
i1    6     4    2000    440      10        20  ;tone 1*tone2
s
i2    0     6    2000    440                    ;tone 1
i2    3     3    2000    881                    ;tone 1+tone2
i1    6     4    2000    440      10       881  ;tone 1*tone2
s
i2    0     6    2000    440                    ;tone 1
i2    3     3    2000   1000                    ;tone 1+tone2
i1    6     4    2000    440      10      1000  ;tone 1*tone2
s
i2    0     6    2000    440                    ;tone 1
i2    3     3    2000   3864                    ;tone 1+tone2
i1    6     4    2000    440      10      3864  ;tone 1*tone2
e
