prompt $G

rem TGROUPED.BAT - batch file to study TEXTURE TGROUPED
rem  notedata outdur skiptime 
rem   snd1st sndlast  mingain maxgain mindur maxdur minpch maxpch
rem    phgrid grpspace gpsprange amprise contour 
rem     gpsizelo gpsizehi gppaklo gppakhi gppranglo gppranghi
rem      [-aatten -ppos -ssprd -rseed -w]

texture tgrouped 3 marimba tgrouped ndftgr2.txt 21 0.5 1 1 40 70 0.25 0.75  48 84 0 1 1 0 0 7 28 75 150 1 7

prompt $P$G
